version: '3.1'
services:
    db:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
        driver: local
